### ISSUE TITLE
current situation on linux

### ISSUE THREAD

**Issue by slynobody** [artur-graniszewski/DLSS-Enabler#1]
First of all thank you very much for your great project!

with a little fiddeling i managed to get dlss working through the winmm-start-option in steam on linux and on the steamdeck on titles like 'hogwarts' and 'jedi survivor', frame-generation does help here to nearly double the framerates. and no ghosting etc.! great.

Could you please provide a list with working titles on windows here?

i saw you had a discussion on nexus-mods concerning watchdogs3, but i did not get it to run on linux yet (not with winmm, not with version/dxgi, not with the reg). same thing with 'no mans sky' , 'uncharted' or 'party animals'.  maybe you have some ideas?

**Comment by slynobody** [comment]
log

[Fri Jul 19 15:29:30] [info] [INIT] Loading of the config file: D:\steamapps\common\WatchDogs_Legion\bin\nvngx.ini
[Fri Jul 19 15:29:30] [info] [INIT] Loading of the config file succeeded
[Fri Jul 19 15:29:30] [info] ==================================================================
[Fri Jul 19 15:29:30] [info] Initializing DLSS Enabler version 3.00.000.0
[Fri Jul 19 15:29:30] [info] ==================================================================
[Fri Jul 19 15:29:30] [info] Running D:\steamapps\common\WatchDogs_Legion\bin\WatchDogsLegion.exe (PID: 1504)
[Fri Jul 19 15:29:30] [info] Running as D:\steamapps\common\WatchDogs_Legion\bin\version.dll
[Fri Jul 19 15:29:30] [info] With arguments: --dlss-nvapi=mock --dlss-debug=extra 
[Fri Jul 19 15:29:30] [info] 
[Fri Jul 19 15:29:30] [info] SYSTEM INFORMATION:
[Fri Jul 19 15:29:30] [info] 
[Fri Jul 19 15:29:30] [info] SYSTEM CHECKS PASSED : 
[Fri Jul 19 15:29:30] [info] + DLSSG to FSR3 module is present (version 0.100)
[Fri Jul 19 15:29:30] [info] 
[Fri Jul 19 15:29:30] [info] SYSTEM CHECKS FAILED:
[Fri Jul 19 15:29:30] [info] - Hardware Accelerated GPU Scheduling misconfigured:
[Fri Jul 19 15:29:30] [info]    - Missing Windows Registry setting
[Fri Jul 19 15:29:30] [info] + NVIDIA Runtime Environment misconfigured
[Fri Jul 19 15:29:30] [info]    - NGX runtime library is configured but file is missing
[Fri Jul 19 15:29:30] [info] 
[Fri Jul 19 15:29:30] [info] NOTICE:
[Fri Jul 19 15:29:30] [info] [INIT] Running Wine 9.0 under Linux 6.5.0-valve13-1-neptune-65-gd5e176bdacb0
[Fri Jul 19 15:29:30] [warning] [INIT] *** Wine 9 support is experimental, some features might be broken
[Fri Jul 19 15:29:30] [info] [HAGS] Enabling Hardware Accelerated GPU Scheduling hooks
[Fri Jul 19 15:29:30] [info] **** DXGI detour done
[Fri Jul 19 15:29:30] [info] [DLSSG] Loading frame generation backend: FSR 3
[Fri Jul 19 15:29:30] [info] [LOADER] Loading D:\steamapps\common\WatchDogs_Legion\bin\nvngx-wrapper.dll
[Fri Jul 19 15:29:30] [info] [LOADER] Loading Streamline interposer module
[Fri Jul 19 15:29:30] [info] [LOADER] Loading Streamline interposer module: failed (error code: 126)
[Fri Jul 19 15:29:30] [error] [LOADER] Tried to load sl.interposer.dll
[Fri Jul 19 15:29:30] [info] [LOADER] Loading Streamline interposer module
[Fri Jul 19 15:29:30] [info] [LOADER] Loading Streamline interposer module: failed (error code: 126)
[Fri Jul 19 15:29:30] [error] [LOADER] Tried to load D:\steamapps\common\WatchDogs_Legion\bin\sl.interposer.dll
[Fri Jul 19 15:29:30] [info] [LOADER] Loading Streamline interposer module
[Fri Jul 19 15:29:30] [info] [LOADER] Loading Streamline interposer module: failed (error code: 126)
[Fri Jul 19 15:29:30] [error] [LOADER] Tried to load D:\steamapps\common\WatchDogs_Legion\bin\..\..\..\Engine\Plugins\Streamline\Binaries\ThirdParty\Win64\sl.interposer.dll
[Fri Jul 19 15:29:30] [info] [LOADER] Loading Streamline interposer module
[Fri Jul 19 15:29:30] [info] [LOADER] Loading Streamline interposer module: failed (error code: 126)
[Fri Jul 19 15:29:30] [error] [LOADER] Tried to load D:\steamapps\common\WatchDogs_Legion\bin\..\..\..\Engine\Plugins\Runtime\Nvidia\Streamline\Binaries\ThirdParty\Win64\sl.interposer.dll
[Fri Jul 19 15:29:30] [info] [LOADER] Loading D:\steamapps\common\WatchDogs_Legion\bin\nvngx-wrapper.dll: succeeded
[Fri Jul 19 15:29:30] [info] [LOADER] Loading D:\steamapps\common\WatchDogs_Legion\bin\dlssg_to_fsr3_amd_is_better.dll
[Fri Jul 19 15:29:30] [info] [LOADER] Loading D:\steamapps\common\WatchDogs_Legion\bin\dlssg_to_fsr3_amd_is_better.dll: succeeded
[Fri Jul 19 15:29:30] [info] [DLSSG] Frame generation backend loaded successfully
[Fri Jul 19 15:29:33] [info] [LOADER] Enabled built-in NVAPI interface!
[Fri Jul 19 15:29:33] [warning] [LOADER] Built-in implementation of NVAPI is still experimental, your application may become unstable!
[Fri Jul 19 15:29:33] [info] [NVAPI] Call to nvapi_QueryInterface detected
[Fri Jul 19 15:29:33] [info] [LOADER] Bundled DXGI API initialized successfully (version 1.60.0)
[Fri Jul 19 15:29:33] [info] [NVAPI] NvAPI_Initialize: GPU selected:     AMD Custom GPU 0405 (RADV VANGOGH) (LUID: 00000000000003f2)
[Fri Jul 19 15:29:33] [info] [NVAPI] NvAPI_Initialize
[Fri Jul 19 15:29:33] [info] [NVAPI] NvAPI_EnumPhysicalGPUs
[Fri Jul 19 15:29:33] [info] [NVAPI] NvAPI_EnumPhysicalGPUs: succeeded
[Fri Jul 19 15:29:33] [info] [NVAPI] NvAPI_GPU_GetPCIIdentifiers
[Fri Jul 19 15:29:33] [info] [NVAPI] NvAPI_GPU_GetPCIIdentifiers: succeeded
[Fri Jul 19 15:29:33] [warning] [NVAPI] NvAPI_Mosaic_EnumDisplayGrids queried but not implemented
[Fri Jul 19 15:29:33] [info] [NVAPI] NvAPI_SYS_GetDriverAndBranchVersion
[Fri Jul 19 15:29:33] [info] [NVAPI] NvAPI_SYS_GetDriverAndBranchVersion: succeeded
[Fri Jul 19 15:29:33] [info] [NVAPI] NvAPI_DISP_GetDisplayIdByDisplayName
[Fri Jul 19 15:29:33] [info] [NVAPI] NvAPI_DISP_GetDisplayIdByDisplayName: succeeded
[Fri Jul 19 15:29:33] [info] [NVAPI] NvAPI_SYS_GetDriverAndBranchVersion
[Fri Jul 19 15:29:33] [info] [NVAPI] NvAPI_SYS_GetDriverAndBranchVersion: succeeded
[Fri Jul 19 15:29:33] [info] [NVAPI] NvAPI_DISP_GetDisplayIdByDisplayName
[Fri Jul 19 15:29:33] [info] [NVAPI] NvAPI_DISP_GetDisplayIdByDisplayName: succeeded
[Fri Jul 19 15:29:36] [info] [NVAPI] NvAPI_SYS_GetDriverAndBranchVersion
[Fri Jul 19 15:29:36] [info] [NVAPI] NvAPI_SYS_GetDriverAndBranchVersion: succeeded
[Fri Jul 19 15:29:36] [info] [NVAPI] NvAPI_DISP_GetDisplayIdByDisplayName
[Fri Jul 19 15:29:36] [info] [NVAPI] NvAPI_DISP_GetDisplayIdByDisplayName: succeeded
[Fri Jul 19 15:29:36] [info] [NVAPI] NvAPI_EnumPhysicalGPUs
[Fri Jul 19 15:29:36] [info] [NVAPI] NvAPI_EnumPhysicalGPUs: succeeded
[Fri Jul 19 15:29:36] [info] [HAGS] D3DKMTEnumAdapters2: called with NumAdapters = 0
[Fri Jul 19 15:29:36] [info] [HAGS] D3DKMTEnumAdapters2: proxied
[Fri Jul 19 15:29:37] [info] [NVAPI] NvAPI_SYS_GetDriverAndBranchVersion
[Fri Jul 19 15:29:37] [info] [NVAPI] NvAPI_SYS_GetDriverAndBranchVersion: succeeded
[Fri Jul 19 15:29:37] [info] [NVAPI] NvAPI_DISP_GetDisplayIdByDisplayName
[Fri Jul 19 15:29:37] [info] [NVAPI] NvAPI_DISP_GetDisplayIdByDisplayName: succeeded
[Fri Jul 19 15:29:37] [info] [HAGS] D3DKMTEnumAdapters2: called with NumAdapters = 0
[Fri Jul 19 15:29:37] [info] [HAGS] D3DKMTEnumAdapters2: proxied

**Comment by artur-graniszewski** [comment]
Hi, the list of supported games can be found here:

https://docs.google.com/spreadsheets/d/1qsvM0uRW-RgAYsOVprDWK2sjCqHnd_1teYAx00_TwUY/edit?gid=1696395655#gid=1696395655

As for Watchdogs, according to your logs - the game doesn't seem to use streamline SDK from NVIDIA for Frame Generation nor NVIDIA NGX API to check any features like DLSS or DLSSG

**Comment by artur-graniszewski** [comment]
His case was weird, my mod does nothing if there's no log entry tagged with [NVNGX]  word.

Here's the documentation on how to read the logs:
https://www.nexusmods.com/site/articles/98
