### ISSUE TITLE
3.02.000.0 BETA 6 testing the new beta

### ISSUE THREAD

**Issue by VelasquezZZ12** [artur-graniszewski/DLSS-Enabler#10]
I did the test here on cyber punk and I had a problem with blurring when moving and it causes aliasing in the background and loss of quality, using RT it gets even worse
I'll test it in other games to see, 
A cool tip would be to be able to turn Reflex emulation on and off using OptiScaler, it would be easier to test right away and see the changes.
test video on youtube link https://www.youtube.com/watch?v=q0eGbeUJT7s&ab_channel=cuttingreaction

**Comment by artur-graniszewski** [comment]
Thanks for testing.

Did you experience the same behavior with any earlier version of the mod?

Also, do you have motion blur enabled in the game settings?

As for the Reflex emulation toggable in the UI, yes, its a very good idea, but will require some help from an author of Optiscaler to add the necessary UI components and pass me the necessary information. I will ask him about that

**Comment by VelasquezZZ12** [comment]
I was using beta 4 and everything worked normally
When I applied beta 6 the dlss option didn't seem the same as it was in the other one, I removed the mod and applied it again and then I went to the DisableNvidiaSignatureChecks option and then I noticed what I thought was strange because it was already right.
I answer your questions version 5 without any problem.
The motion blur was the same as the other version and I also noticed that the shadow that remains when it is in the car has increased.
Does this fanstama have a solution?

**Comment by artur-graniszewski** [comment]
Ok. The only file that could make a difference here is called dlss-enabler-upscaler.dll

After installing beta6 please overwrite this file with the one from either beta4 or beta5 and tell me if things improve.

Its especially important to understand what was the latest version of this file that works correctly

**Comment by VelasquezZZ12** [comment]
Using beta 6, as you can see in the video, you can see that the application doesn't look great on Wukong, maybe test it on other games and I'll send it to you to see the results.
I recorded the initial part of the game and then off in the vegetation to see but it didn't look good using the beta, testing the upscaler it loses a lot of quality and the character gains an area around him with glitches or drag, I finished the game using beta 4. It was perfect, it even fixes the shadows that the game has without using RT
https://www.youtube.com/watch?v=zYriHkcnafk

**Comment by VelasquezZZ12** [comment]
> Ok. O único arquivo que pode fazer a diferença aqui é chamado dlss-enabler-upscaler.dll
> 
> Após instalar o beta6, substitua este arquivo pelo do beta4 ou beta5 e me diga se as coisas melhoraram.
> 
> É especialmente importante entender qual é a versão mais recente deste arquivo que funciona corretamente

I did the test by applying beta 6 and then replacing it with beta 5 and then 4.
I had the impression that beta 4 was better, but if you apply beta 4 only the result is better
