### ISSUE TITLE
testing beta10 with Reflex emulation on and off FINAL FANTASY XVI and GOW

### ISSUE THREAD

**Issue by VelasquezZZ12** [artur-graniszewski/DLSS-Enabler#11]
I edit videos for a website so I always pick up games at launch to test lol
I tested beta 7 and also the normal mod and I had this problem, I think it's character synchronization.
I also tested the reflex, it's great and the mod's upscaler is better than the game's, I just had this error.
https://www.youtube.com/watch?v=oO1Iq3FYMz4

**Comment by artur-graniszewski** [comment]
Ah. Unfortunately I heard similar thing happened to real DLSS FG some time ago (without my mod obviously).

I could imagine things, but I think I accidentally stumbled upon a youtube video few months ago which was claiming to show how to fix that issue for DLSS (didn't watch it on details, just the beginnig of it,that's why I recognize this issue) . After that I couldn't find it on purpose.

**Comment by alex-riverack** [comment]
@VelasquezZZ12 it is far worse on low-end spec devices like the Steam Deck, btw does it crash after some minutes of gameplay? it just freezes after some time (music keeps playing), I had to revert back to Beta 4 on my Steam Deck.

**Comment by VelasquezZZ12** [comment]
> @VelasquezZZ12é muito pior em dispositivos de especificações mais baixas, como o Steam Deck. Aliás, ele trava depois de alguns minutos de jogo? Ele simplesmente congela depois de algum tempo (a música continua tocando), tive que voltar para o Beta 4 no meu Steam Deck.

beta 4 is perfect but the version is not cool yet

**Comment by artur-graniszewski** [comment]
Could you try setting "ReflexEmulation=on" in nvngx.ini? (its almost at the top of that file). This disables AntiLag2 and LatencyFlex for latency reduction. I wonder if this soft lock is related to this functionality

**Comment by alexriveraz** [comment]
I tried beta 7 with "ReflexEmulation=on" as you previously mentioned and had the game running for nearly 2 hours without issues. I will give beta 8 a try now.

**Comment by artur-graniszewski** [comment]
> I tried beta 7 with "ReflexEmulation=on" as you previously mentioned and had the game running for nearly 2 hours without issues. I will give beta 8 a try now.

Thanks, remember to use default Reflex settings to make sure we're not testing again the workaround from BETA7 (so in short, it should be "ReflexEmulation=auto", which reactivates AntiLag2 and LFX).

**Comment by alexriveraz** [comment]
@artur-graniszewski I’m still getting soft locks with beta 8 but now it crashes my Steam Deck when I try to close the game after pressing the “STEAM” button

**Comment by artur-graniszewski** [comment]
> @artur-graniszewski I’m still getting soft locks with beta 8 but now it crashes my Steam Deck when I try to close the game after pressing the “STEAM” button Edit: Testing in Desktop Mode and it's working just fine, it seems something may not be working for me in Game Mode, need more testing, I'll update this later.

thanks, please also double check if the previous beta7 trick solves the issue in beta8 in non-desktop mode. We need to isolate the issue and confirm its all because of Reflex or something else...

**Comment by alexriveraz** [comment]
@artur-graniszewski Yes, applying the beta 7 workaround on beta 8 solves the issue in non-desktop mode too.

**Comment by artur-graniszewski** [comment]
Ok. Beta 9 has just been released, please check it without this workaround please.

**Comment by alexriveraz** [comment]
@artur-graniszewski well I was able to play for around 30 minutes before a soft lock in game mode on my SD, and also it didn’t hard crash now to “Verify Installation” like in beta 9, it’s an improvement. Need to cold boot and make another test.

**Comment by VelasquezZZ12** [comment]
> Ah. Infelizmente, ouvi dizer que algo parecido aconteceu com o DLSS FG real há algum tempo (sem meu mod, obviamente).
> 
> Eu poderia imaginar coisas, mas acho que acidentalmente tropecei em um vídeo do YouTube alguns meses atrás que alegava mostrar como consertar esse problema para DLSS (não assisti em detalhes, apenas o começo, é por isso que reconheço esse problema). Depois disso, não consegui encontrá-lo de propósito.

I did the test in the same game and also in the gow that came out, in the gow there were no problems and it ran perfectly now in ff16 it is much better than before but there is still a small flaw but it is 100% better than before just a small synchronization error still let's say that to be perfect, 5% is missing, also test Reflex emulation off and I noticed the frame time change
