### ISSUE TITLE
problems encountered in the new version 3.03.000.0 TRUNK

### ISSUE THREAD

**Issue by VelasquezZZ12** [artur-graniszewski/DLSS-Enabler#18]
problems in the new version of the mod using amd gpu.
using the dxgi and wimm option, with dxgi it does not enable dlss in the game and wimm does not open
![Crash Dump Sending Utility 02_10_2024 17_07_30](https://github.com/user-attachments/assets/dbe71a76-a6b6-43a3-94c5-2792eebac5e8)
![Warhammer 40,000_ Space Marine 2 CLIENT 3 0 W1 360000_360274 02_10_2024 17_03_25](https://github.com/user-attachments/assets/ef78df2e-0818-4c48-bbae-a4817de4b8ee)

**Comment by artur-graniszewski** [comment]
Uh, sorry about that, its a development build and I forgot to tick the checbox saying its not a stable release (just fixed that).

**Comment by VelasquezZZ12** [comment]
I tested Outlaws using amd and there was a lot of ghosting in version 3.02.000.0 then I removed it and put the version dlss-enabler-setup-3.03.000.0-trunk, the game opened normally then I chose the upscaler ok when I went to activate the fg the hud stayed bad and soon after when activating the fps the fps dropped to 20 and without it it was normal, so I went to use the game's fg disconnected from the mod and closed the game
[dlss-enabler-setup-3.03.000.0-trunk.log](https://github.com/user-attachments/files/17237931/dlss-enabler-setup-3.03.000.0-trunk.log)
[OptiScale11.log](https://github.com/user-attachments/files/17237933/OptiScale11.log)

**Comment by artur-graniszewski** [comment]
Ok. Thanks, there seems to be an error related to Swapchain. Will forward this to Nitec.

**Comment by artur-graniszewski** [comment]
I talked to Nitec and he wonders if  you enabled in-game FG when testing the FG provided by OptiScaler. If so, please try to avoid running two different FGs at the same time.

**Comment by VelasquezZZ12** [comment]
done as you requested, using the new version available https://www.youtube.com/watch?v=bIEryyPOc4E
