### ISSUE TITLE
testing the normal and beta version on rdr1

### ISSUE THREAD

**Issue by VelasquezZZ12** [artur-graniszewski/DLSS-Enabler#27]
I tried to apply the normal version of dlss enabler and also "beta" but the game seems to have this error here, would there be any correction tips?

[dlssg_to_fsr3.log](https://github.com/user-attachments/files/17559701/dlssg_to_fsr3.log)

[OptiScaler.log](https://github.com/user-attachments/files/17559704/OptiScaler.log)

![WhatsApp Image 2024-10-29 at 12 35 05](https://github.com/user-attachments/assets/e57afd25-2446-4d7e-a916-01528ee6d3d0)

**Comment by JSTT05** [comment]
lo resolviste?

**Comment by VelasquezZZ12** [comment]
yes, use the version of dlss enabler 3.2 that will work, then you turn off vsinc and activate nvidia low latency then the fg will unlock in the game
