### ISSUE TITLE
 support for Black Myth Wukong?

### ISSUE THREAD

**Issue by VelasquezZZ12** [artur-graniszewski/DLSS-Enabler#4]
Will there be native support for Black Myth Wukong?
because I tested it, the FG synchronization was strange and also the hair on the character and other textures were strange, just like when there is no sharpness

**Comment by jeevithakannan2** [comment]
Did DLSS frame generation work for you

**Comment by artur-graniszewski** [comment]
> Will there be native support for Black Myth Wukong? because I tested it, the FG synchronization was strange and also the hair on the character and other textures were strange, just like when there is no sharpness

The app is already supported, especially 8n the beta builds. You can use optiscaler to tweak the sharpness of the image. As for the other artefacts - I would have to see them to suggest any solution.

**Comment by artur-graniszewski** [comment]
https://github.com/artur-graniszewski/DLSS-Enabler/releases/tag/3.01.001.0-beta11

**Comment by VelasquezZZ12** [comment]
> A geração de quadros DLSS funcionou para você? Estou usando Linux e não está funcionando

I'm using Win and the FG works but there are sometimes ghots problems on the hud and artifacts on the character

**Comment by VelasquezZZ12** [comment]
> > Haverá suporte nativo para Black Myth Wukong? porque eu testei, a sincronização do FG estava estranha e também o cabelo do personagem e outras texturas estavam estranhas, assim como quando não há nitidez
> 
> O aplicativo já é suportado, especialmente nas compilações beta. Você pode usar o optiscaler para ajustar a nitidez da imagem. Quanto aos outros artefatos, eu teria que vê-los para sugerir alguma solução.

I have an artifact on the character and vegetation, is it also possible to use a reshader with the mod?

**Comment by artur-graniszewski** [comment]
> > > Haverá suporte nativo para Black Myth Wukong? porque eu testei, a sincronização do FG estava estranha e também o cabelo do personagem e outras texturas estavam estranhas, assim como quando não há nitidez
> > 
> > 
> > O aplicativo já é suportado, especialmente nas compilações beta. Você pode usar o optiscaler para ajustar a nitidez da imagem. Quanto aos outros artefatos, eu teria que vê-los para sugerir alguma solução.
> 
> I have an artifact on the character and vegetation, is it also possible to use a reshader with the mod?

Yes, rename dxgi.dll provided by Reshade to d3d12.dll, and both mods will work together nicely.

**Comment by VelasquezZZ12** [comment]
I did this and it worked correctly, thank you very much 
But I have this problem in the game, so I made this video to demonstrate
link youtube https://www.youtube.com/watch?v=zggH0mnMxCI
How can I solve it?

**Comment by artur-graniszewski** [comment]
Hi, 

this is a well known bug in game engine. Just make sure your in-game screen resolution matches the actual display resolution.

**Comment by willymai** [comment]
i got error with DLSS and Frame Generation `On`

is it known issue @artur-graniszewski ?
https://github.com/user-attachments/assets/7ea757b7-4f44-4c73-973a-2b7abdfc6446

**Comment by artur-graniszewski** [comment]
> > > Haverá suporte nativo para Black Myth Wukong? porque eu testei, a sincronização do FG estava estranha e também o cabelo do personagem e outras texturas estavam estranhas, assim como quando não há nitidez
> > 
> > 
> > O aplicativo já é suportado, especialmente nas compilações beta. Você pode usar o optiscaler para ajustar a nitidez da imagem. Quanto aos outros artefatos, eu teria que vê-los para sugerir alguma solução.
> 
> I have an artifact on the character and vegetation, is it also possible to use a reshader with the mod?



> > > Haverá suporte nativo para Black Myth Wukong? porque eu testei, a sincronização do FG estava estranha e também o cabelo do personagem e outras texturas estavam estranhas, assim como quando não há nitidez
> > 
> > 
> > O aplicativo já é suportado, especialmente nas compilações beta. Você pode usar o optiscaler para ajustar a nitidez da imagem. Quanto aos outros artefatos, eu teria que vê-los para sugerir alguma solução.
> 
> I have an artifact on the character and vegetation, is it also possible to use a reshader with the mod?

According to some comment on Nexus, latest AMD drivers solve the blue artifacts in this game:

> for Black myth: wukong, if you have installed the drivers 24.8.1 or below, this will happen. try updating to the latest beta of the drivers "AFMF 24.20.11.01" this drivers have the bug fixed for Wukong and you can use medium to cinematic without problems.

**Comment by willymai** [comment]
> sorry, the video quality is a bit low, could you explain the error to me?

Issue is fixed by changing resolution from 1280x800 to 1280x720, and flickering issue in bottom screen is fixed @artur-graniszewski
