### ISSUE TITLE
Is it possible to setup solid 30fps or 40fps (plan to set this on steam deck_ ?

### ISSUE THREAD

**Issue by Mupli** [artur-graniszewski/DLSS-Enabler#7]
Well I tried to limit fps count but frame pacing is all over the place. 
Is it possible to make it more solid?

**Comment by artur-graniszewski** [comment]
Hi, is it just about frame time graph or the frame pacing is really a perceived problem?

**Comment by Mupli** [comment]
(I meant frame pacing). 
for 30fps frame-time should be 33.3ms. 
for 40fps 25.0ms /  (max 38.0ms/ min 7.0 ms
for unlocked  I seen from 41fps to 56fps. 

Even if fps shows this correct numbers. The game camera tells me otherwise. 

I see stuttering on locked and on disabled fps. It would be nice to lock the game on 20fps and framegeneration on 30fps. with perfect framepace.

In DLSS UI I see  on 20fps (49/50ms) but why the frame generation is jumping crazy. 

Platform: Linux Steam OS (Steam Deck)

**Comment by artur-graniszewski** [comment]
Depending on the test results, newest build of DLSS Enabler will be equipped with LatencyFlex solution. This should improve both the frame pacing and responsiveness of every game.

![image](https://github.com/user-attachments/assets/e554b5fd-de20-47b7-bb62-109d477064e6)

**Comment by Mupli** [comment]
Yeah I see the improvement. But yeah.. it would be nice to say "give me crystal steady 30ms!".
